# This is a basic workflow to help you get started with Actions

name: Deploy to GitHub Pages

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-to-github-pages:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Sets up .NET Core SDK 3.1
      - name: Setup .NET Core SDK 3.1
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 3.1

      # Publish Blazor project to release-folder
      - name: Publish .Net Core Project
        run: dotnet publish SynergySearch/SynergySearch.csproj -c Release -o release
        
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-actions@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
